Update alll

diff --git a/croptiff b/croptiff
--- a/croptiff
+++ b/croptiff
@@ -1,11 +1,15 @@
 #!/bin/bash
 
-msg() { printf "croptiff: %s\n" "$*" > /dev/stderr; }
+msg()   { printf "croptiff: %s\n" "$*" > /dev/stderr; }
+usage() { printf 'usage: croptiff <px> <py> <tiff file>\n' > /dev/stderr; exit 1; }
+die()   { printf 'croptiff: %s\n' "$*"; usage; }
+
 # [a]wk [e]xpression: ae 1.0+2.0 returns 3.0
 ae() ( s='BEGIN {print '"$@"'}'; awk "$s" )
 ini () { # uses `px' and `py' to set `lx' and `ly', `dx', `dy'
     local f=$1
     lx=`convert $f -format '%w' info:`
+    if test $? != 0; then die wrong image: $f; fi
     ly=`convert $f -format '%h' info:`
     msg old size: $lx $ly
 
@@ -27,9 +31,10 @@ run() {
 t=/tmp/croptiff.$$.tiff
 trap 'rm -rf $t' 1 2 3 15
 
-px=$1; shift
-py=$1; shift
+px=$1; shift; if test $# = 0; then die 'arg count'; fi
+py=$1; shift; if test $# = 0; then die 'arg count'; fi
+
+if ! test -r "$1"; then die "cannot read $1"; fi
 
 ini $1
-
 for f; do run "$f"; done
